version: "3"

services:

  gateone:
    build: ./ttyd
    ports:
    - "7681:7681"
    hostname: kubectl
    networks:
    - frontend
    volumes:
    - ssh_key:/root/.ssh/
    - /root/.kube/:/root/.kube/

  lab:
    build: ./lab
    entrypoint: /opt/entry.bash
    ports:
      - 80:80
    networks:
    - frontend
    environment:
      GATEONE_HTTP_SERVER: "localhost:7681"

networks:
  frontend: {}
volumes:
  ssh_key: {}
